#python /home/matwilso/code/boxLCD/research/main.py --mode=eval --env=Luxo --datadir=logs/datadump/fill/comprehensive/Luxo/ --arbiterdir=logs/april22/arbiter/Luxo --model=FlatBToken --lr=5e-4 --log_n=1000 --bs=32 --nfilter=64 --hidden_size=300 --window=50 --total_itr=100000 --free_nats=0.01 --prompt_n=3 --weightdir=logs/april22a/video/FlatBToken/Luxo/ --logdir=logs/april22/evaler/FIT_Luxo --bs=500

#python /home/matwilso/code/boxLCD/research/main.py --mode=eval --env=LuxoCube --datadir=logs/datadump/fill/comprehensive/LuxoCube/ --arbiterdir=logs/april22/arbiter/LuxoCube --model=FlatBToken --lr=5e-4 --log_n=1000 --bs=32 --nfilter=64 --hidden_size=300 --window=50 --total_itr=100000 --free_nats=0.01 --prompt_n=3 --weightdir=logs/april22a/video/FlatBToken/LuxoCube/ --logdir=logs/april22/evaler/FIT_LuxoCube --bs=500

#python /home/matwilso/code/boxLCD/research/main.py --mode=eval --env=Urchin --datadir=logs/datadump/fill/comprehensive/Urchin/ --arbiterdir=logs/april22/arbiter/Urchin --model=FlatBToken --lr=5e-4 --log_n=1000 --bs=32 --nfilter=64 --hidden_size=300 --window=50 --total_itr=100000 --free_nats=0.01 --prompt_n=3 --weightdir=logs/april28/video/FlatBToken/Urchin/ --logdir=logs/april22/evaler/april28/FIT_Urchin --bs=500
python /home/matwilso/code/boxLCD/research/main.py --mode=eval --env=UrchinCube --datadir=logs/datadump/fill/comprehensive/UrchinCube/ --arbiterdir=logs/april22/arbiter/UrchinCube --model=FlatBToken --lr=5e-4 --log_n=1000 --bs=32 --nfilter=64 --hidden_size=300 --window=50 --total_itr=100000 --free_nats=0.01 --prompt_n=3 --weightdir=logs/april28/video/FlatBToken/UrchinCube/ --logdir=logs/april22/evaler/april28/FIT_UrchinCube --bs=500
p
python /home/matwilso/code/boxLCD/research/main.py --mode=eval --env=Luxo --datadir=logs/datadump/fill/comprehensive/Luxo/ --arbiterdir=logs/april22/arbiter/Luxo --model=FlatBToken --lr=5e-4 --log_n=1000 --bs=32 --nfilter=64 --hidden_size=300 --window=50 --total_itr=100000 --free_nats=0.01 --prompt_n=3 --weightdir=logs/april28/video/FlatBToken/Luxo/ --logdir=logs/april22/evaler/april28/FIT_Luxo --bs=500
python /home/matwilso/code/boxLCD/research/main.py --mode=eval --env=LuxoCube --datadir=logs/datadump/fill/comprehensive/LuxoCube/ --arbiterdir=logs/april22/arbiter/LuxoCube --model=FlatBToken --lr=5e-4 --log_n=1000 --bs=32 --nfilter=64 --hidden_size=300 --window=50 --total_itr=100000 --free_nats=0.01 --prompt_n=3 --weightdir=logs/april28/video/FlatBToken/LuxoCube/ --logdir=logs/april22/evaler/april28/FIT_LuxoCube --bs=500
